SQLALCHEMY_DATABASE_PATH: "/mnt/c/Users/francischen/Development/pslx/example/frontend_example/frontend_example.db"
CONTAINER_BACKEND_CONFIG:
  SERVER_URL: "localhost:11443"
  ROOT_CERTIFICATE_PATH: ""
PROTO_VIEWER_CONFIG:
  SERVER_1:
    SERVER_URL: "localhost:11444"
    ROOT_CERTIFICATE_PATH: ""
FILE_VIEWER_CONFIG:
  SERVER_1:
    SERVER_URL: "localhost:11445"
    ROOT_CERTIFICATE_PATH: ""
USER_NAME: "guest"
PASSWORD: "guest"
