site_name: 'PSLX documentation'
site_author: 'Kaifeng Chen'

repo_name: 'kfrancischen/pslx'
repo_url: 'https://github.com/kfrancischen/pslx'

copyright: 'Copyright &copy; 2020 Kaifeng Chen'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/kfrancischen'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/kaifeng-chen-b37a2b69/'

python:
   version: 3 # for unicode
   setup_py_install: true

markdown_extensions:
    - toc:
        permalink: true
    - fenced_code
    - codehilite
    - footnotes
    - admonition

pages:
- Home: 'index.md'
- Job Scheduling: 'container.md'
- Data Storage: 'storage.md'
- RPC: 'rpc.md'
- Micro Services:
    - 'Instant Messaging': 'micro_services/instant_messaging.md'
    - 'Email': 'micro_services/email.md'
    - 'RPC Storage IO': 'micro_services/rpc_storage_io.md'
    - 'Message Queue': 'micro_services/message_queue.md'
    - 'PSLX frontend': 'micro_services/frontend.md'
- Tools: 'tool.md'
- Utilities: 'util.md'
- TTL Cleaner: 'ttl_cleaner.md'
- Proto Schema: 'schema.md'

theme: 'material'